name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"

      - name: Build container
        run: ./scripts/buildprod.sh

      - name: Set up Google Cloud
        uses: 'google-github-actions/setup-gcloud@v3.0.0'
        with:
          project_id: notely-504219
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: build and push container to GCP Artifact Registry
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-504219/notely-ar-repo/notely:latest